services:
  - type: web
    name: twitch-clipbot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TWITCH_CLIENT_ID
        sync: true
      - key: TWITCH_CLIENT_SECRET
        sync: true
      - key: TWITCH_REFRESH_TOKEN
        sync: true
      - key: TWITCH_BROADCASTER_ID
        sync: true
      - key: DISCORD_WEBHOOK_URL
        sync: true
