services:
  - type: web
    name: twitch_clipbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: DISCORD_WEBHOOK_URL
        sync: true
      - key: TWITCH_CLIENT_ID
        sync: true
      - key: TWITCH_BROADCASTER_ID
        sync: true
